- hosts: server-a
  remote_user: ubuntu
  become: yes
  tasks: 
    - name: update apt 
      apt:
        update_cache: yes
    
    - name: creating directory 
      file:
        name: jenkins_home
        state: directory
        mode: 0777

    - name: installing java 
      apt:
        name: openjdk-8-jdk 
        state: present

    - name: install curl package
      apt: 
        pkg: 
         - curl 

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker

    # sudo groupadd docker
    - name: Create "docker" group
      group:
        name: "docker"
        state: present

    # sudo usermod -aG docker root
    - name: Add remote "ubuntu" user to "docker" group
      user:
        name: "ubuntu"
        groups: "docker"
        append: yes
    
    - name: Creating bin directory 
      file: 
        path: /home/ubuntu/bin
        state: directory
        mode: 0777
    
    - name: copying the agent jar to the slave 
      copy:
        src:  agent.jar
        dest: /home/ubuntu/bin/agent.jar
  
    - name: install git 
      apt:
        name: git
        state: latest
       
# coniguring ssh, jdk like what we did on docker slave 
# ansible-playbook --private-key aws-slave.pem -i inventory ansible-ec2.yml